//! Create and configure AI agent spending accounts on Squads Protocol v4.
//!
//! The core entry point is [`create_governed_spending_account`], which performs
//! four sequential on-chain transactions (TX1–TX4):
//!
//! 1. **TX1** — `multisig_create_v2`: creates the multisig with a temporary
//!    bootstrap `configAuthority` equal to `payer.pubkey()`.
//! 2. **TX2** — `multisig_add_spending_limit`: attaches a per-period lamport cap,
//!    signed by the bootstrap `configAuthority`.
//! 3. **TX3** — `multisig_change_threshold`: sets the governance threshold,
//!    signed by the bootstrap `configAuthority`.
//! 4. **TX4** — `multisig_set_config_authority`: permanently disables the
//!    `configAuthority` by setting it to [`Pubkey::default()`].
//!
//! # Bug fixes preserved from the TypeScript proof-of-concept
//!
//! - **BUG FIX #1**: Treasury is always read from the live on-chain
//!   [`squads_multisig_program::state::ProgramConfig`] account, never assumed
//!   to be the payer's own keypair.
//! - **BUG FIX #2**: [`Period`] uses the Rust enum variant (e.g. `Period::Day`),
//!   never a raw struct literal or integer constant.
//! - **BUG FIX #3**: The `configAuthority` null sentinel is [`Pubkey::default()`]
//!   (the all-zero System Program address), not a language-level `None`/`null`.

use solana_client::nonblocking::rpc_client::RpcClient;
use solana_sdk::{
    instruction::{AccountMeta, Instruction},
    pubkey::Pubkey,
    signature::{Keypair, Signature},
    signer::Signer,
    system_program,
    transaction::Transaction,
};
use squads_multisig::{
    anchor_lang::{AccountDeserialize, InstructionData},
    client::{multisig_create_v2, MultisigCreateAccountsV2, MultisigCreateArgsV2},
    pda::{get_multisig_pda, get_program_config_pda, get_spending_limit_pda, get_vault_pda},
    squads_multisig_program as program,
    state::{Member, Period, Permission, Permissions},
};

// BUG FIX #1: use the state::ProgramConfig, not instructions::ProgramConfig.
// At the program crate root, `pub use instructions::ProgramConfig` shadows the
// state type, so we must reach through the full path.
use squads_multisig::squads_multisig_program::state::ProgramConfig as ProgramConfigState;

// Instruction data types generated by Anchor for TX2/TX3/TX4.
// These are NOT exposed in squads_multisig::client (which only wraps the
// proposal/vote/execute flow). We build them manually via InstructionData.
use squads_multisig::squads_multisig_program::instruction::{
    MultisigAddSpendingLimit as MultisigAddSpendingLimitIx,
    MultisigChangeThreshold as MultisigChangeThresholdIx,
    MultisigSetConfigAuthority as MultisigSetConfigAuthorityIx,
};
use squads_multisig::squads_multisig_program::{
    MultisigAddSpendingLimitArgs, MultisigChangeThresholdArgs, MultisigSetConfigAuthorityArgs,
};

use crate::error::CerberusError;

// ── Public types ──────────────────────────────────────────────────────────────

/// On-chain addresses returned after a successful governed spending account setup.
///
/// All three PDAs are derived deterministically from the `create_key` generated
/// during setup. They are stable — no need to persist the `create_key` after
/// a successful [`create_governed_spending_account`] call.
#[derive(Debug, Clone)]
pub struct SpendingAccount {
    /// Squads v4 multisig PDA governing the agent wallet.
    pub multisig_pda: Pubkey,
    /// Squads v4 vault PDA (vault index 0) from which the agent transacts.
    pub vault_pda: Pubkey,
    /// Spending limit PDA enforcing the per-period lamport cap.
    pub spending_limit_pda: Pubkey,
}

/// Per-period spending cap configuration for an AI agent wallet.
#[derive(Debug, Clone)]
pub struct SpendingTierConfig {
    /// Maximum lamports the agent may spend in a single reset period.
    /// Must be greater than zero.
    pub max_auto_approve_lamports: u64,
    /// How frequently the spending limit resets.
    pub period: SpendingPeriod,
    /// SPL token mint. Use [`Pubkey::default()`] for native SOL.
    pub mint: Pubkey,
}

/// Reset period for a Squads v4 spending limit.
///
/// Maps one-to-one to [`squads_multisig::state::Period`]. Only these four
/// variants exist in the on-chain program (v4 has no `Year` variant).
///
/// # BUG FIX #2
///
/// Always convert via [`From<SpendingPeriod> for Period`] to use the typed
/// enum variant. Never construct `Period` from a raw integer or struct literal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SpendingPeriod {
    /// One-time spending limit (never auto-resets).
    OneTime,
    /// Resets every 24 hours.
    Day,
    /// Resets every 7 days.
    Week,
    /// Resets every 30 days.
    Month,
}

impl From<SpendingPeriod> for Period {
    /// BUG FIX #2: uses the typed Rust enum variant, never a raw value.
    fn from(p: SpendingPeriod) -> Self {
        match p {
            SpendingPeriod::OneTime => Period::OneTime,
            SpendingPeriod::Day => Period::Day,
            SpendingPeriod::Week => Period::Week,
            SpendingPeriod::Month => Period::Month,
        }
    }
}

// ── Public API ────────────────────────────────────────────────────────────────

/// Creates a fully locked, governed spending account for an AI agent wallet.
///
/// Sends four sequential on-chain transactions (TX1–TX4). When this call
/// returns successfully:
/// - The multisig `configAuthority` is permanently set to [`Pubkey::default()`].
/// - No party can change the spending limit without a multisig vote from
///   `governing_authority`.
///
/// The returned [`SpendingAccount`] contains all PDA addresses needed to
/// route transactions and verify the setup.
///
/// # Parameters
///
/// - `rpc`: Async Solana RPC client (devnet or mainnet).
/// - `payer`: Keypair paying all rent and fees. Must be funded.
/// - `agent_wallet`: AI agent pubkey that will call `spending_limit_use`.
/// - `governing_authority`: Human pubkey who votes on multisig proposals.
/// - `tier`: Spending cap (amount, period, mint).
///
/// # Errors
///
/// - [`CerberusError::InvalidSpendingLimitAmount`] if `tier.max_auto_approve_lamports == 0`.
/// - [`CerberusError::DeserializationError`] if the on-chain `ProgramConfig` is malformed.
/// - [`CerberusError::RpcError`] on any network failure.
/// - [`CerberusError::LockVerificationFailed`] if the lock is not confirmed after TX4.
///
/// # Example
///
/// ```rust,no_run
/// use cerberus_skill::{
///     create_governed_spending_account,
///     spending_account::{SpendingTierConfig, SpendingPeriod},
/// };
/// use solana_client::nonblocking::rpc_client::RpcClient;
/// use solana_sdk::{pubkey::Pubkey, signature::Keypair, signer::Signer};
///
/// # #[tokio::main]
/// # async fn main() -> Result<(), cerberus_skill::error::CerberusError> {
/// let rpc = RpcClient::new("https://api.devnet.solana.com".to_string());
/// let payer = Keypair::new();
/// let agent = Keypair::new().pubkey();
/// let authority = Keypair::new().pubkey();
///
/// let account = create_governed_spending_account(
///     &rpc,
///     &payer,
///     agent,
///     authority,
///     SpendingTierConfig {
///         max_auto_approve_lamports: 10_000_000,
///         period: SpendingPeriod::Day,
///         mint: Pubkey::default(),
///     },
/// ).await?;
///
/// println!("multisig: {}", account.multisig_pda);
/// println!("vault:    {}", account.vault_pda);
/// # Ok(())
/// # }
/// ```
pub async fn create_governed_spending_account(
    rpc: &RpcClient,
    payer: &Keypair,
    agent_wallet: Pubkey,
    governing_authority: Pubkey,
    tier: SpendingTierConfig,
) -> Result<SpendingAccount, CerberusError> {
    if tier.max_auto_approve_lamports == 0 {
        return Err(CerberusError::InvalidSpendingLimitAmount {
            reason: "max_auto_approve_lamports must be greater than zero".to_string(),
        });
    }

    // Generate a fresh create_key for this setup. Losing it after a successful
    // setup is fine — the PDA addresses are returned in SpendingAccount.
    let create_key = Keypair::new();
    let (multisig_pda, _) = get_multisig_pda(&create_key.pubkey(), Some(&program::ID));
    let (vault_pda, _) = get_vault_pda(&multisig_pda, 0, Some(&program::ID));
    let (spending_limit_pda, _) =
        get_spending_limit_pda(&multisig_pda, &create_key.pubkey(), Some(&program::ID));

    // BUG FIX #1: fetch treasury from the live on-chain ProgramConfig.
    let treasury = fetch_treasury(rpc).await?;

    // TX1 — multisig_create_v2
    create_multisig_bootstrap(
        rpc,
        payer,
        &create_key,
        agent_wallet,
        governing_authority,
        &multisig_pda,
        &treasury,
    )
    .await?;

    // TX2 — multisig_add_spending_limit
    add_spending_limit(
        rpc,
        payer,
        &multisig_pda,
        &create_key,
        &spending_limit_pda,
        agent_wallet,
        &tier,
    )
    .await?;

    // TX3 — multisig_change_threshold (confirms 1-of-1 governance)
    raise_threshold(rpc, payer, &multisig_pda, 1).await?;

    // TX4 — multisig_set_config_authority → Pubkey::default()
    // BUG FIX #3: the sentinel is Pubkey::default(), not None.
    disable_config_authority(rpc, payer, &multisig_pda).await?;

    // Verify the lock was fully applied before returning.
    crate::verify::assert_fully_locked(rpc, &multisig_pda, 1).await?;

    Ok(SpendingAccount {
        multisig_pda,
        vault_pda,
        spending_limit_pda,
    })
}

/// TX1: Creates the Squads v4 multisig with a bootstrap `configAuthority`.
///
/// Sets `configAuthority = payer.pubkey()` so TX2/TX3/TX4 can be signed
/// without going through the multisig proposal flow. TX4 permanently disables
/// this authority.
///
/// Members configured:
/// - `governing_authority`: full permissions (`Initiate | Vote | Execute`).
/// - `agent_wallet`: `Initiate | Execute` — can use the spending limit and
///   execute approved proposals, but cannot influence governance votes.
///
/// # Errors
///
/// Returns [`CerberusError::RpcError`] on any RPC or transaction failure.
pub async fn create_multisig_bootstrap(
    rpc: &RpcClient,
    payer: &Keypair,
    create_key: &Keypair,
    agent_wallet: Pubkey,
    governing_authority: Pubkey,
    multisig_pda: &Pubkey,
    treasury: &Pubkey,
) -> Result<Signature, CerberusError> {
    let (program_config_pda, _) = get_program_config_pda(Some(&program::ID));

    let members = vec![
        // The human approver: full governance control.
        Member {
            key: governing_authority,
            permissions: Permissions::from_vec(&[
                Permission::Initiate,
                Permission::Vote,
                Permission::Execute,
            ]),
        },
        // The AI agent: can initiate and execute, but cannot vote on config changes.
        // Must be a multisig member to appear in spending_limit.members (TX2 validates this).
        Member {
            key: agent_wallet,
            permissions: Permissions::from_vec(&[Permission::Initiate, Permission::Execute]),
        },
    ];

    let ix = multisig_create_v2(
        MultisigCreateAccountsV2 {
            program_config: program_config_pda,
            treasury: *treasury,
            multisig: *multisig_pda,
            create_key: create_key.pubkey(),
            creator: payer.pubkey(),
            system_program: system_program::id(),
        },
        MultisigCreateArgsV2 {
            members,
            threshold: 1,
            // Bootstrap configAuthority: payer can sign TX2/TX3/TX4 directly.
            // TX4 will set this to Pubkey::default() to permanently disable it.
            config_authority: Some(payer.pubkey()),
            rent_collector: None,
            time_lock: 0,
            memo: None,
        },
        Some(program::ID),
    );

    send_tx(rpc, &[ix], payer, &[payer, create_key]).await
}

/// TX2: Attaches a spending limit to the multisig.
///
/// Signed by `payer` acting as the bootstrap `configAuthority` from TX1.
/// The instruction data is built using the Anchor [`InstructionData`] trait
/// on `MultisigAddSpendingLimitIx`, since this instruction is not exposed in
/// `squads_multisig::client` (which only wraps the proposal/vote/execute flow).
///
/// # Errors
///
/// Returns [`CerberusError::RpcError`] on any RPC or transaction failure.
pub async fn add_spending_limit(
    rpc: &RpcClient,
    payer: &Keypair,
    multisig_pda: &Pubkey,
    create_key: &Keypair,
    spending_limit_pda: &Pubkey,
    agent_wallet: Pubkey,
    tier: &SpendingTierConfig,
) -> Result<Signature, CerberusError> {
    let ix_data = MultisigAddSpendingLimitIx {
        args: MultisigAddSpendingLimitArgs {
            create_key: create_key.pubkey(),
            vault_index: 0,
            mint: tier.mint,
            amount: tier.max_auto_approve_lamports,
            // BUG FIX #2: use the typed enum variant, never a raw value.
            period: tier.period.into(),
            members: vec![agent_wallet],
            destinations: vec![],
            memo: None,
        },
    }
    .data();

    // Account metas verified against squads-multisig-program-2.0.0 source:
    // - multisig: NOT writable (no `mut` on the seeds constraint).
    // - config_authority: readonly signer.
    // - spending_limit: writable (init).
    // - rent_payer: writable signer (same as config_authority here).
    // - system_program: readonly.
    let accounts = vec![
        AccountMeta::new_readonly(*multisig_pda, false),
        AccountMeta::new_readonly(payer.pubkey(), true),
        AccountMeta::new(*spending_limit_pda, false),
        AccountMeta::new(payer.pubkey(), true),
        AccountMeta::new_readonly(system_program::id(), false),
    ];

    let ix = Instruction {
        program_id: program::ID,
        accounts,
        data: ix_data,
    };

    send_tx(rpc, &[ix], payer, &[payer]).await
}

/// TX3: Sets the multisig governance threshold.
///
/// Signed by `payer` acting as the bootstrap `configAuthority`.
/// Call this before [`disable_config_authority`] to confirm the desired
/// threshold is on-chain. After [`disable_config_authority`] succeeds, the
/// threshold can only be changed via a multisig vote.
///
/// # Parameters
///
/// - `new_threshold`: Target threshold. Must satisfy `1 <= new_threshold <= num_voters`.
///   With the default member setup from [`create_multisig_bootstrap`],
///   `governing_authority` is the only voter, so `new_threshold` must be `1`.
///
/// # Errors
///
/// Returns [`CerberusError::RpcError`] on any RPC or transaction failure.
pub async fn raise_threshold(
    rpc: &RpcClient,
    payer: &Keypair,
    multisig_pda: &Pubkey,
    new_threshold: u16,
) -> Result<Signature, CerberusError> {
    let ix_data = MultisigChangeThresholdIx {
        args: MultisigChangeThresholdArgs {
            new_threshold,
            memo: None,
        },
    }
    .data();

    // Account metas for MultisigConfig (TX3/TX4):
    // - multisig: writable (mut on seeds constraint).
    // - config_authority: readonly signer.
    // - rent_payer: Option<Signer> — None for operations that don't reallocate.
    //   Anchor convention: pass program::ID as the null-sentinel key.
    // - system_program: Option<Program<System>> — None, same sentinel.
    let accounts = vec![
        AccountMeta::new(*multisig_pda, false),
        AccountMeta::new_readonly(payer.pubkey(), true),
        AccountMeta::new_readonly(program::ID, false),
        AccountMeta::new_readonly(program::ID, false),
    ];

    let ix = Instruction {
        program_id: program::ID,
        accounts,
        data: ix_data,
    };

    send_tx(rpc, &[ix], payer, &[payer]).await
}

/// TX4: Permanently disables the multisig `configAuthority`.
///
/// Sets `config_authority` to [`Pubkey::default()`] (the all-zero System Program
/// address). After this call, the on-chain `Multisig` account has no privileged
/// admin — every configuration change requires a multisig vote.
///
/// # BUG FIX #3
///
/// The `configAuthority` null sentinel MUST be [`Pubkey::default()`].
/// In the TypeScript proof-of-concept, passing JavaScript `null` did not
/// correctly encode to the all-zero sentinel, leaving the authority active.
/// In Rust, [`Pubkey::default()`] is always the correct value.
///
/// # Errors
///
/// Returns [`CerberusError::RpcError`] on any RPC or transaction failure.
pub async fn disable_config_authority(
    rpc: &RpcClient,
    payer: &Keypair,
    multisig_pda: &Pubkey,
) -> Result<Signature, CerberusError> {
    // BUG FIX #3: Pubkey::default() is the sentinel for "no config authority".
    // The on-chain Multisig.config_authority field is Pubkey (not Option<Pubkey>),
    // and Squads v4 treats Pubkey::default() (all zeros) as "autonomous multisig".
    let ix_data = MultisigSetConfigAuthorityIx {
        args: MultisigSetConfigAuthorityArgs {
            config_authority: Pubkey::default(),
            memo: None,
        },
    }
    .data();

    let accounts = vec![
        AccountMeta::new(*multisig_pda, false),
        AccountMeta::new_readonly(payer.pubkey(), true),
        AccountMeta::new_readonly(program::ID, false),
        AccountMeta::new_readonly(program::ID, false),
    ];

    let ix = Instruction {
        program_id: program::ID,
        accounts,
        data: ix_data,
    };

    send_tx(rpc, &[ix], payer, &[payer]).await
}

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Fetches the Squads v4 `ProgramConfig` account and returns the `treasury` pubkey.
///
/// # BUG FIX #1
///
/// Never assume the treasury equals any local keypair. The treasury address is
/// configured by the Squads Protocol team and must be read from chain at runtime.
async fn fetch_treasury(rpc: &RpcClient) -> Result<Pubkey, CerberusError> {
    let (program_config_pda, _) = get_program_config_pda(Some(&program::ID));
    let account = rpc.get_account(&program_config_pda).await?;

    let config =
        ProgramConfigState::try_deserialize(&mut account.data.as_slice()).map_err(|e| {
            CerberusError::DeserializationError {
                address: program_config_pda.to_string(),
                message: e.to_string(),
            }
        })?;

    Ok(config.treasury)
}

/// Signs and sends a transaction, confirming it before returning its signature.
async fn send_tx(
    rpc: &RpcClient,
    instructions: &[Instruction],
    fee_payer: &Keypair,
    signers: &[&Keypair],
) -> Result<Signature, CerberusError> {
    let recent_blockhash = rpc.get_latest_blockhash().await?;
    let tx = Transaction::new_signed_with_payer(
        instructions,
        Some(&fee_payer.pubkey()),
        signers,
        recent_blockhash,
    );
    Ok(rpc.send_and_confirm_transaction(&tx).await?)
}
